# Generated by Django 5.2.6 on 2025-09-04 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aporte', models.CharField(choices=[('ECONOMICO', 'Económico'), ('TRABAJO', 'Trabajo'), ('PRODUCTO', 'Producto')], max_length=20)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha_aporte', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aporte',
                'verbose_name_plural': 'Aportes',
                'ordering': ['-fecha_aporte'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_socio', models.CharField(choices=[('PRODUCTOR', 'Productor'), ('CONSUMIDOR', 'Consumidor'), ('TRABAJADOR', 'Trabajador')], max_length=20)),
                ('dni', models.CharField(help_text='DNI del socio (solo números)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener solo números (8-15 dígitos)', regex='^\\d{8,15}$')])),
                ('direccion', models.TextField(max_length=500)),
                ('telefono', models.CharField(help_text='Teléfono del socio (solo números)', max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener solo números (7-15 dígitos)', regex='^\\d{7,15}$')])),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
