# Generated by Django 5.2.6 on 2025-09-04 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socio_perfil', to='usuarios.user'),
        ),
        migrations.AddField(
            model_name='aporte',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='socios.socio'),
        ),
        migrations.AddIndex(
            model_name='socio',
            index=models.Index(fields=['dni'], name='socio_dni_idx'),
        ),
        migrations.AddIndex(
            model_name='socio',
            index=models.Index(fields=['activo'], name='socio_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='socio',
            index=models.Index(fields=['tipo_socio'], name='socio_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='aporte',
            index=models.Index(fields=['tipo_aporte'], name='aporte_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='aporte',
            index=models.Index(fields=['fecha_aporte'], name='aporte_fecha_idx'),
        ),
    ]
