# Generated by Django 5.2.5 on 2025-09-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='dni',
            field=models.CharField(blank=True, help_text='DEPRECATED: Usar documento_identidad en su lugar', max_length=20, null=True, unique=True),
        ),
    ]
