# Generated by Django 5.2.5 on 2025-09-08 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CI', 'Cédula de Identidad'), ('NIT', 'Número de Identificación Tributaria'), ('PASAPORTE', 'Pasaporte'), ('CARNET_EXTRANJERO', 'Carnet de Extranjero')], default='CI', max_length=20)),
                ('numero_documento', models.CharField(help_text='Número del documento sin guiones ni espacios', max_length=20)),
                ('extension', models.CharField(blank=True, help_text='Extensión del documento (ej: 1A para CI)', max_length=5, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento de Identidad',
                'verbose_name_plural': 'Documentos de Identidad',
                'db_table': 'documentos_identidad',
                'indexes': [models.Index(fields=['tipo_documento', 'numero_documento'], name='documentos__tipo_do_25205d_idx'), models.Index(fields=['numero_documento'], name='documentos__numero__4b4d79_idx'), models.Index(fields=['activo'], name='documentos__activo_81178f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('tipo_documento', 'numero_documento', 'extension'), name='unique_documento_completo'), models.UniqueConstraint(condition=models.Q(('activo', True), ('extension__isnull', True)), fields=('tipo_documento', 'numero_documento'), name='unique_documento_sin_extension')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='documento_identidad',
            field=models.OneToOneField(blank=True, help_text='Documento de identidad del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='usuarios.documentoidentidad'),
        ),
    ]
